[phases.install]
cmds = ["mkdir -p /var/log/nginx /var/cache/nginx", "composer install --ignore-platform-reqs --no-scripts --no-interaction --prefer-dist"]

[phases.build]
cmds = ["composer dump-autoload --optimize --classmap-authoritative --no-interaction"]
